DalWorth/Server/Dalworth.Server/Dalworth.Server.Web.Partner/Controllers/UserSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dalworth.Server.Domain;
using Dalworth.Server.Web.Partner.Models;

namespace Dalworth.Server.Web.Partner.Controllers
{
    public class UserSettingsController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("PersonalInfo");
        }

        public ActionResult PersonalInfo()
        {
            return View(new PersonalInfoModel());
        }
    
        [HttpPost]
        public ActionResult PersonalInfo(PersonalInfoModel personalInfo)
        {
            if (personalInfo != null && ModelState.IsValid)
            {                
                string errorText = personalInfo.Save();
                if (errorText != string.Empty)
                    ModelState.AddModelError("", errorText);
                else
                    return RedirectToAction("CallLog", "Home");
            }

            return PersonalInfo();
        }

        public ActionResult ManagePhones()
        {
            WebUser currentUser = PartnerMembershipProvider.GetCurrentUser();
            if (!currentUser.OrderSourceId.HasValue)
                return RedirectToAction("CallLog", "Home");

            return View(new PhoneInfoModel());
        }

        public ActionResult Delete(int id)
        {
            PhoneInfoModel phoneModel = new PhoneInfoModel();
            phoneModel.DeleteOwnPhone(id);
            return RedirectToAction("ManagePhones");
        }

        public ActionResult AddPhone()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult AddPhone(OwnPhone newPhone)
        {
            if (newPhone != null && ModelState.IsValid)
            {
                PhoneInfoModel phoneModel = new PhoneInfoModel();
                string errorText = phoneModel.AddOwnPhone(newPhone.PhoneNumber);
                if (errorText != string.Empty)
                    ModelState.AddModelError("", errorText);
                else
                    return RedirectToAction("ManagePhones");
            }            

            return View();
        }
    }
}

DalWorth/Server/Dalworth.Server/Dalworth.Server.Web.Partner/Views/UserSettings/AddPhone.cshtml
@model Dalworth.Server.Web.Partner.Models.OwnPhone

@{
    ViewBag.Title = "Partner In Profit - Add Personal Phone";
    ViewBag.Header = "Add Personal Phone";

}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("AddPhone", "UserSettings", FormMethod.Post, new { id = "AddPhoneForm" })) {
    if (!MvcHtmlString.IsNullOrEmpty(Html.ValidationSummary(true))){
		<div id="message-red">
		<table border="0" width="500px" cellpadding="0" cellspacing="0">
		<tr>
			<td class="red-left">
                @Html.ValidationSummary(true)
			<td class="red-right"><a class="close-red"><img src="../Content/images/table/icon_close_red.gif"   alt="" /></a></td>
		</tr>
		</table>
		</div>        
    }       

	<table border="0" cellpadding="0" cellspacing="0"  id="id-form">
    <tr>
		<th valign="top">Phone Number</th>
		<td>
            @Html.TextBoxFor(model => model.PhoneNumber, new { @class="field-input" })            
        </td>
		<td>
            @Html.ValidationMessageFor(model => model.PhoneNumber)
        </td>
	</tr>

	<tr>
		<th>&nbsp;</th>
		<td valign="top">
			<input type="submit" value="" class="form-submit" />			
		</td>
		<td></td>
	</tr>

    </table>
}
@Html.ActionLink("Back to Manage Phones", "ManagePhones", new { controller = "UserSettings" }, new { @class="back-link" })

DalWorth/Server/Dalworth.Server/Dalworth.Server.Web.Partner/Views/UserSettings/ManagePhones.cshtml
@model Dalworth.Server.Web.Partner.Models.PhoneInfoModel

@{
    ViewBag.Title = "Partner In Profit - Manage Phones";
    ViewBag.Header = "Manage Phones";
}

<table>
<tr>    
    <td valign="top">
    
        <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
            <tr>
                <th class="table-header-repeat line-left" colspan="2">Personal Phones</th>
            </tr>

        @if (Model.OwnPhones.Count == 0){
        <tr><td colspan="100">Empty</td></tr>
        }

        @foreach (var item in Model.OwnPhones) {
            <tr>
                <td width="100px">
                    @item.NumberText        
                </td>
                <td>
                    @Html.ActionLink(" ", "Delete", new { id=item.ID }, new { @class = "icon-2 info-tooltip" })
                </td>
            </tr>
        }
        </table>
    </td>
    <td width="100px"></td>
    <td valign="top">
        <table border="0" width="100%" cellpadding="0" cellspacing="0" id="product-table">
            <tr>
                <th class="table-header-repeat line-left">Tracking Phones</th>
            </tr>

        @if (Model.TrackingPhones.Count == 0){
        <tr><td colspan="100">Empty</td></tr>
        }

        @foreach (var item in Model.TrackingPhones) {
            <tr>
                <td>
                    @item.NumberText
                </td>
            </tr>
        }

        </table>

    </td>
</tr>
</table>


<p></p>



<p>
@Html.ActionLink("Add Personal Phone", "AddPhone", new { controller = "UserSettings" }, new { @class="back-link" })    
</p>

DalWorth/Server/Dalworth.Server/Dalworth.Server.Web.Partner/Views/UserSettings/PersonalInfo.cshtml
@model Dalworth.Server.Web.Partner.Models.PersonalInfoModel

@{
    ViewBag.Title = "Partner In Profit - Personal Info";
    ViewBag.Header = "Personal Info";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("PersonalInfo", "UserSettings", FormMethod.Post, new { id = "PersonalInfoForm" })) {
    @Html.ValidationSummary(true)

	<table border="0" cellpadding="0" cellspacing="0"  id="id-form">
	<tr>
		<th valign="top">Partner Name</th>
		<td>
            @Model.OrderSource
        </td>
		<td></td>
	</tr>

	<tr>
		<th valign="top">Email</th>
		<td>
            @Model.Email
        </td>
		<td></td>
	</tr>	

    <tr>
		<th valign="top">First Name</th>
		<td>
            @Html.TextBoxFor(model => model.FirstName, new { @class="field-input" })            
        </td>
		<td>
            @Html.ValidationMessageFor(model => model.FirstName)
        </td>
	</tr>

    <tr>
		<th valign="top">Last Name</th>
		<td>
            @Html.TextBoxFor(model => model.LastName, new { @class="field-input" })            
        </td>
		<td>
            @Html.ValidationMessageFor(model => model.LastName)
        </td>
	</tr>

	<tr>
		<th>&nbsp;</th>
		<td valign="top">
			<input type="submit" value="" class="form-submit"/>
		</td>
		<td></td>
	</tr>

    </table>

}